### ISSUE TITLE
Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/recink#102]
Reference: http://jenkins.cloudnativeci.com:8080/job/2W_Clarivate_Terraform/131/console

When executing `recink run terraform -vv --custom-config="wos_gipp.terraform.apply:true"`, we are getting the following error:

```
22:29:48 stack: 
22:29:48   - TypeError: Cannot read property 'hasOwnProperty' of undefined
22:29:48   -     at DotObject.str (/var/lib/jenkins/.nvm/versions/node/v8.9.1/lib/node_modules/recink/node_modules/dot-object/index.js:164:19)
22:29:48   -     at Function.str (/var/lib/jenkins/.nvm/versions/node/v8.9.1/lib/node_modules/recink/node_modules/dot-object/index.js:74:31)
22:29:48   -     at transformConfig (/var/lib/jenkins/.nvm/versions/node/v8.9.1/lib/node_modules/recink/bin/commands/run/generic.js:84:13)
22:29:48   -     at recink.configureExtend.then.config (/var/lib/jenkins/.nvm/versions/node/v8.9.1/lib/node_modules/recink/bin/commands/run/generic.js:177:25)
22:29:48   -     at <anonymous>
```

Please help us fix this issue.

**Comment by eistrati** [comment]
Checked.
