### ISSUE TITLE
Install on windows doesn't work

### ISSUE THREAD

**Issue by sergius0301** [MitocGroup/recink#13]
Environment Windows 10 Pro

```
D:\Work\run-jst-master>npm install -g run-jst
C:\Users\sergiu0301\AppData\Roaming\npm\jst -> C:\Users\sergiu0301\AppData\Roaming\npm\node_modules\run-jst\bin\cli.js

> spawn-sync@1.0.15 postinstall C:\Users\sergiu0301\AppData\Roaming\npm\node_modules\run-jst\node_modules\spawn-sync
> node postinstall


> caporal@0.5.0 postinstall C:\Users\sergiu0301\AppData\Roaming\npm\node_modules\run-jst\node_modules\caporal
> (test -f ./node_modules/husky/bin/install.js && node ./node_modules/husky/bin/install.js) || exit 0

'test' is not recognized as an internal or external command,
operable program or batch file.

> run-jst@1.4.0 postinstall C:\Users\sergiu0301\AppData\Roaming\npm\node_modules\run-jst
> node node-bin/ensure-peer-dependencies.js

Ensure peerDependencies are installed
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
C:\Users\sergiu0301\AppData\Roaming\npm
`-- (empty)

npm WARN run-jst@1.4.0 requires a peer of travis-lint@^1.0.0 but none was installed.
npm WARN run-jst@1.4.0 requires a peer of travis-encrypt@MitocGroup/node-travis-encrypt but none was installed.
npm WARN run-jst@1.4.0 requires a peer of github-slug@^2.0.0 but none was installed.
npm WARN run-jst@1.4.0 requires a peer of parse-github-repo-url@^1.4.0 but none was installed.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! run-jst@1.4.0 postinstall: `node node-bin/ensure-peer-dependencies.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the run-jst@1.4.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sergiu0301\AppData\Roaming\npm-cache\_logs\2017-06-08T16_33_43_354Z-debug.log

```

**Comment by AlexanderC** [comment]
Please upvote. Waiting for at least `10` 👍 to start.

**PR**s are welcome ;)

**Comment by eistrati** [comment]
Closing as out of scope for now. Feel free to post your comments and use cases if this is relevant to you. If there is enough interest, we might consider to reopen this issue.
