### ISSUE TITLE
Cannot read property 'inherit' of undefined

### ISSUE THREAD

**Issue by ddimitrioglo** [MitocGroup/recink#43]
Receiving `Cannot read property 'inherit' of undefined` on `The command "recink run unit -c recink-codeclimate -c recink-snyk" exited with 1` 

Repo: Adtechmedia/adtechmedia-website

```
stack: 
  """
    TypeError: Cannot read property 'inherit' of undefined
        at Object.<anonymous> (/home/travis/build/AdTechMedia/adtechmedia-website/src/adtechmedia-website/backend/src/email/send/node_modules/deep-core/node_modules/aws-sdk/lib/service.js:4:23)
        at SandboxedModule._compile (/home/travis/.nvm/versions/node/v6.11.0/lib/node_modules/recink/node_modules/sandboxed-module/lib/sandboxed_module.js:251:19)
        at createInnerSandboxedModule (/home/travis/.nvm/versions/node/v6.11.0/lib/node_modules/recink/node_modules/sandboxed-module/lib/sandboxed_module.js:183:23)
        at SandboxedModule.RecursiveRequireProxy (/home/travis/.nvm/versions/node/v6.11.0/lib/node_modules/recink/node_modules/sandboxed-module/lib/sandboxed_module.js:214:27)
        at Object.<anonymous> (/home/travis/build/AdTechMedia/adtechmedia-website/src/adtechmedia-website/backend/src/email/send/node_modules/deep-core/node_modules/aws-sdk/lib/core.js:73:1)
        at SandboxedModule._compile (/home/travis/.nvm/versions/node/v6.11.0/lib/node_modules/recink/node_modules/sandboxed-module/lib/sandboxed_module.js:251:19)
        at createInnerSandboxedModule (/home/travis/.nvm/versions/node/v6.11.0/lib/node_modules/recink/node_modules/sandboxed-module/lib/sandboxed_module.js:183:23)
        at SandboxedModule.RecursiveRequireProxy (/home/travis/.nvm/versions/node/v6.11.0/lib/node_modules/recink/node_modules/sandboxed-module/lib/sandboxed_module.js:214:27)
        at Object.<anonymous> (/home/travis/build/AdTechMedia/adtechmedia-website/src/adtechmedia-website/backend/src/email/send/node_modules/deep-core/node_modules/aws-sdk/lib/aws.js:1:79)
        at SandboxedModule._compile (/home/travis/.nvm/versions/node/v6.11.0/lib/node_modules/recink/node_modules/sandboxed-module/lib/sandboxed_module.js:251:19)
  """
```

**Comment by AlexanderC** [comment]
@ref https://travis-ci.org/AdTechMedia/adtechmedia-website/jobs/265576128
