### ISSUE TITLE
Run modules partially

### ISSUE THREAD

**Issue by ddimitrioglo** [MitocGroup/recink#72]
Add an ability to run test modules partially

**Comment by avozicov** [comment]
"Skips modules" is implemented and works as expected.
Steps to test:
- clone latest recink code to your local (if it's not released to npm yet)
- run "npm install -g (path to recink code)"
- run the execution with the following parameter "recink run unit --skip-modules='module_name' "

Expected result:
- skipped module should not be processed

Please refer to attachment for more details:
(lib business rules module is skipped according the parameter value)  
<img width="667" alt="screen shot 2017-11-09 at 14 05 10" src="https://user-images.githubusercontent.com/12330493/32606211-21821658-c55d-11e7-944c-b65120fd1d16.png">

**Comment by avozicov** [comment]
Please refer to the updated README for more details
https://github.com/MitocGroup/recink/blob/master/docs/faq.md

**Comment by eistrati** [comment]
@ddimitrioglo Let's rename `--skip-modules` into `--exclude-modules` and add functionality that will correspond to parameter `--include-modules`

**Comment by eistrati** [comment]
Not functional. Let's address them after the other priorities.

**Comment by eistrati** [comment]
```
./recink run terraform -vv --include-modules=wos_dev_qa2_us_west_2_rds_restore --tf-vars=instances_class.0:db.t2.micro...

Initialize components registry in /var/lib/jenkins/.recink/generic/registry.json

Loading components - preprocess, npm, cache, emit, terraform

Load component preprocess

Load component npm

Load component cache

Load component emit

Load component terraform

Component preprocess is subscribed

Component npm is subscribed

Component cache is subscribed

Component emit is subscribed

Component terraform is subscribed

Preprocess $.terraform.vars.access_key using - eval

Preprocess $.terraform.vars.secret_key using - eval

Preprocess $.terraform.vars.region using - eval

Component preprocess is ready


message: us is not defined
stack: 
  - ReferenceError: us is not defined
  -     at eval (eval at transform (/var/lib/jenkins/workspace/deploy-wos-restore-rds-from-snapshot/node_modules/recink/src/component/preprocess/eval-transformer.js:17:17), <anonymous>:1:1)
  -     at EvalTransformer.transform (/var/lib/jenkins/workspace/deploy-wos-restore-rds-from-snapshot/node_modules/recink/src/component/preprocess/eval-transformer.js:17:12)
  -     at preprocessors.map.reduce (/var/lib/jenkins/workspace/deploy-wos-restore-rds-from-snapshot/node_modules/recink/src/component/preprocess-component.js:59:51)
  -     at Array.reduce (native)
  -     at Object.keys.map.configPath (/var/lib/jenkins/workspace/deploy-wos-restore-rds-from-snapshot/node_modules/recink/src/component/preprocess-component.js:58:62)
  -     at Array.map (native)
  -     at Object.emitter.onBlocking.config [as listener] (/var/lib/jenkins/workspace/deploy-wos-restore-rds-from-snapshot/node_modules/recink/src/component/preprocess-component.js:49:36)
  -     at Recink._dispatch (/var/lib/jenkins/workspace/deploy-wos-restore-rds-from-snapshot/node_modules/recink/src/emitter.js:202:31)
  -     at _waitAllowParallel.then (/var/lib/jenkins/workspace/deploy-wos-restore-rds-from-snapshot/node_modules/recink/src/emitter.js:40:24)
Build step 'Execute shell' marked build as failure
```

**Comment by ddimitrioglo** [comment]
@eistrati I've made some debugging but could not reproduce the issue, but I've fixed some config parsing issue, let's see if it helped

**Comment by eistrati** [comment]
Checked.
