### ISSUE TITLE
Error loading file: no such file or directory

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/recink#79]
```bash
message: 
  """
    Command failed: /var/lib/jenkins/workspace/deploy-datafactory-dii-app/bin/terraform show -no-color /var/lib/jenkins/workspace/deploy-datafactory-dii-app/cc-dev/wos-content/datafactory/dev/dii-app-user-data-2/.resource/terraform.tfstate
    Error loading file: open /var/lib/jenkins/workspace/deploy-datafactory-dii-app/cc-dev/wos-content/datafactory/dev/dii-app-user-data-2/.resource/terraform.tfstate: no such file or directory
    
    
  """
stack: 
  - Error: Command failed: /var/lib/jenkins/workspace/deploy-datafactory-dii-app/bin/terraform show -no-color /var/lib/jenkins/workspace/deploy-datafactory-dii-app/cc-dev/wos-content/datafactory/dev/dii-app-user-data-2/.resource/terraform.tfstate
  - Error loading file: open /var/lib/jenkins/workspace/deploy-datafactory-dii-app/cc-dev/wos-content/datafactory/dev/dii-app-user-data-2/.resource/terraform.tfstate: no such file or directory
  - 
  - 
  -     at Promise.all.then.arr (/var/lib/jenkins/.nvm/versions/node/v8.9.1/lib/node_modules/recink-terraform/node_modules/execa/index.js:236:11)
  -     at <anonymous>
  -     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by eistrati** [comment]
Checked.
